#-------------------------------
# General Site Settings
title: Hartoyo Wahyu
logo: # You can add own logo. For example '/images/logo.png'.
description: Random musings of a slightly crazed engineer of society.
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: plankton
  avatar: '/images/profiles/profile.jpeg'


#-------------------------------
# Hero Settings
hero:
  title: Hartoyo Wahyu
  description: Detection Engineering & Threat Hunting
  image: '/images/profiles/profile.jpeg'


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion ion-logo-github", link: "https://github.com/hrtywhy"}
- {icon: "ion ion-logo-linkedin", link: "https://www.linkedin.com/in/planktonz/"}



#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: G-65VG6MD5LY # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /blog/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 18
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


collections:
  quotes:
    output: true
    permalink: /quotes/:path/